### ISSUE TITLE
update to use podman instead of docker

### ISSUE THREAD

**Issue by thisdwhitley** [thisdwhitley/ansible-role-KSbuilder#4]
I can do this with the command module but I should see if there's a podman module for this

```
- name: when the kickstart will be hosted by an nginx container
  block:
    - name: open up a port if specified
      become: yes
      firewalld:
        port: "{{ ks.container_port }}/tcp"
        immediate: true
        state: enabled

    - name: start a nginx container to house KS
      become: true
      command: 'podman run --rm -d -p {{ ks.container_port }}:80 -v /tmp/KS:/usr/share/nginx/html:Z --name nginxKS nginx'
```

I probably should explore whether it is necessary to run this as root too...I don't think it should be necessary.
